services:
  crm-app:
    build: .
    restart: always
    ports:
      - 8001:8000
    volumes:
      - .:/code
    environment:
      DEBUG: False
      CELERY_BROKER_URL_: pyamqp://guest@rabbitmq//
      CELERY_RESULT_BACKEND_: db+postgresql://postgres:postgres@postgres/crm_tables
      DB_HOST: postgres
    depends_on:
      - postgres
      - rabbitmq
  postgres:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
