# Generated by Django 4.1.7 on 2023-06-21 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_companies', '0003_company_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
