# Generated by Django 4.1.7 on 2023-02-21 12:07

import crm_for_companies.api_employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(validators=[crm_for_companies.api_employees.models.validate_age]),
        ),
    ]
